apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: gitops
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:3.68.0-java11
        ports:
        - containerPort: 8081
        - containerPort: 8082  
      - name: sidecar
        image: nginx:1.26.0-alpine3.19-slim
        command:
            - /bin/sh
            - -c
            - |
              export DOMAIN1="nexus1.albertcoronado.com"
              export DOMAIN2="repo1.albertcoronado.com"

              if ! ping -4 -c 1 "$DOMAIN1" > /dev/null; then echo "Dominio no disponible"; sleep infinity; fi

              apk add certbot

              certbot certonly \
                -d "$DOMAIN1","$DOMAIN2" \
                --noninteractive \
                --standalone \
                --agree-tos \
                --register-unsafely-without-email || true

              echo 'worker_processes  1; events { worker_connections  1024; }' > /etc/nginx/nginx.conf
              echo 'http { include mime.types; default_type application/octet-stream; sendfile on; keepalive_timeout  65;' >> /etc/nginx/nginx.conf
              echo 'server { listen 80 default_server; return 301 https://$host$request_uri; }' >> /etc/nginx/nginx.conf
              echo 'server { listen 443 ssl; server_name '$DOMAIN1'; client_max_body_size 1000M; location / { resolver 127.0.0.1 [::1]:8081 valid=30s; proxy_pass http://127.0.0.1:8081; proxy_redirect off; proxy_set_header Host $host; } ssl_certificate /etc/letsencrypt/live/'$DOMAIN1'/fullchain.pem; ssl_certificate_key /etc/letsencrypt/live/'$DOMAIN1'/privkey.pem; ssl_protocols TLSv1 TLSv1.1 TLSv1.2; ssl_ciphers HIGH:!aNULL:!MD5; }' >> /etc/nginx/nginx.conf
              echo 'server { listen 443 ssl; server_name '$DOMAIN2'; client_max_body_size 1000M; location / { resolver 127.0.0.1 [::1]:8082 valid=30s; proxy_pass http://127.0.0.1:8082; proxy_redirect off; proxy_set_header Host $host; } ssl_certificate /etc/letsencrypt/live/'$DOMAIN1'/fullchain.pem; ssl_certificate_key /etc/letsencrypt/live/'$DOMAIN1'/privkey.pem; ssl_protocols TLSv1 TLSv1.1 TLSv1.2; ssl_ciphers HIGH:!aNULL:!MD5; }' >> /etc/nginx/nginx.conf
              echo '}' >> /etc/nginx/nginx.conf

              nginx -g 'daemon off;' || true

              sleep infinity
        ports:
        - containerPort: 80
        - containerPort: 443  

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: gitops
spec:
  type: LoadBalancer
  ports:
  - name: nexus-http
    port: 80
  - name: nexus-repository
    port: 443    
  selector:
    app: nexus