---
- name: Install the NFS package
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Setup NFS for k8s
  ansible.builtin.shell: |
    if [[ ! -d /nexus-data && $(! grep -q '/nexus-data' /etc/exports; echo $?) ]]; then
        mkdir -p /nexus-data
        chmod o+rwx /nexus-data
        chown -R nobody: /nexus-data
        {
          echo '/nexus-data   *(rw,sync,no_root_squash,no_all_squash)'
        } | tee -a /etc/exports
        systemctl restart nfs-kernel-server
    else
        echo 'Existing NFS config detected. Not applying changes'
    fi
    # showmount -e
  args:
    executable: /bin/bash

