---
- name: Install NFS for the clients
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Setup NFS for Wordpress BS
  ansible.builtin.shell: |
    if [ ! -d /opt/registry ]; then
      mkdir -p /opt/{certs,registry}
      {
        echo "hostnfs:/opt/certs    /opt/certs    nfs defaults 0 0"
        echo "hostnfs:/opt/registry /opt/registry nfs defaults 0 0"
      } | tee -a /etc/fstab
      mount -a
    fi
    # df -h
  args:
    executable: /bin/bash


# OJO: lo de 'host_nfs' no será aplicable hasta que se ejecute el script post-ansible
