---
- name: Install NFS for the clients
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Setup NFS clients in k8s
  ansible.builtin.shell: |
    if [ ! -d /nexus-data ]; then
      mkdir -p /nexus-data
      {
        echo "hostnfs:/nexus-data    /nexus-data    nfs defaults 0 0"
      } | tee -a /etc/fstab
      mount -a
    fi
    # df -h
  args:
    executable: /bin/bash

