---
- name: master - dotfiles
  hosts: master
  become: true
  roles:
    - dotfiles

- name: all vms - kubernetes
  hosts: remote
  become: true
  roles:
    - kubernetes
  handlers:
    - name: docker status
      service: name=docker state=started
