---
# - name: nfs vm - setup nfs
#   hosts: hostnfs
#   become: true
#   roles:
#     - nfs-server

- name: cluster vms - nfs client & k8s script
  hosts: cluster
  become: true
  # roles:
    # - nfs-client
    # - ssh
  tasks:
    - name: files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/{{ item }}
        owner: root
        group: root
        mode: '0644'
      loop:
        - k8s-jotelulu.sh

- name: master - dotfiles & manifests
  hosts: master
  become: true
  roles:
    # - repo
    - dotfiles
  # tasks:
  #   - name: Ensure /nexus directory exists
  #     ansible.builtin.file:
  #       path: /nexus
  #       state: directory
  #       owner: root
  #       group: root
  #       mode: '0755'

  #   - name: Copy k8s manifests to /nexus
  #     ansible.builtin.copy:
  #       src: nexus
  #       dest: /
  #       owner: root
  #       group: root
  #       mode: '0644'

# - name: master - kubeadm init
# - name: master - kubeadm join


# - name: rancher vm - install docker for Rancher
#   hosts: hostrancher
#   become: true
#   roles:
#     - kubernetes
#   handlers:
#     - name: docker status
#       service: name=docker state=started