# -*- mode: ruby -*-
# vi: set ft=ruby :
cluster = {
  "host01" => { :ip => "192.168.61.69", :cpus => 2, :mem => 4096 },
  "host02" => { :ip => "192.168.61.248", :cpus => 2, :mem => 4096 },
  "host03" => { :ip => "192.168.61.247", :cpus => 2, :mem => 2048 },
  "host04" => { :ip => "192.168.61.4", :cpus => 2, :mem => 2048 }
}
groups = {
  "remote" => ["host01","host02","host03","host04"],
  "rancher" => ["host01"],
  "master" => ["host02"],
  "workers" => ["host03","host04"]
}

Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian12"
    cluster.each do |name, data|
      config.vm.define name do |host|
        host.vm.hostname = name
        host.vm.network "private_network", ip: "#{data[:ip]}"
        host.vm.provider :virtualbox do |vb, override|
          vb.cpus = data[:cpus]
          vb.memory = data[:mem]
        end
      end
    end
    config.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "playbook.yaml"
      ansible.groups = groups
    end
  end
